// eslint-disable-next-line @typescript-eslint/no-unused-vars
// import { IObservableArray, ObservableMap } from 'mobx';

export { Instance } from './core/state/Instance';
export { SnapshotIn, SnapshotOut } from './core/state/Snapshot';

export { IType, IAnyType } from './core/type/Type';
export { ISimpleType } from './core/type/SimpleType';
export { IAnyComplexType } from './core/type/ComplexType';
export { isType } from './core/type/type-utils';

/* all code is initially loaded through internal, to avoid circular dep issues */
export {
  IModelType,
  IAnyModelType,
  IDisposer,
  IMSTMap,
  IMapType,
  IMSTArray,
  IArrayType,
  ModelPrimitive,
  IReferenceType,
  _CustomCSProcessor,
  _CustomOrOther,
  _CustomJoin,
  _NotCustomized,
  typecheck,
  escapeJsonPath,
  unescapeJsonPath,
  joinJsonPath,
  splitJsonPath,
  IJsonPatch,
  IReversibleJsonPatch,
  decorate,
  addMiddleware,
  IMiddlewareEvent,
  IMiddlewareHandler,
  IMiddlewareEventType,
  isStateTreeNode,
  IStateTreeNode,
  IAnyStateTreeNode,
  flow,
  castFlowReturn,
  applyAction,
  onAction,
  IActionRecorder,
  ISerializedActionCall,
  recordActions,
  setLivelinessChecking,
  getLivelinessChecking,
  LivelinessMode,
  ModelSnapshotType,
  ModelCreationType,
  ModelSnapshotType2,
  ModelCreationType2,
  ModelInstanceType,
  ModelInstanceTypeProps,
  ModelPropertiesDeclarationToProperties,
  ModelProperties,
  ModelPropertiesDeclaration,
  ModelActions,
  ITypeUnion,
  CustomTypeOptions,
  UnionOptions,
  TypeOrStateTreeNodeToStateTreeNode,
  UnionStringArray,
  getType,
  getChildType,
  onPatch,
  onSnapshot,
  applyPatch,
  IPatchRecorder,
  recordPatches,
  protect,
  unprotect,
  isProtected,
  applySnapshot,
  getSnapshot,
  hasParent,
  getParent,
  hasParentOfType,
  getParentOfType,
  getRoot,
  getPath,
  getPathParts,
  isRoot,
  resolvePath,
  resolveIdentifier,
  getIdentifier,
  tryResolve,
  getRelativePath,
  clone,
  detach,
  destroy,
  isAlive,
  addDisposer,
  getEnv,
  walk,
  IModelReflectionData,
  IModelReflectionPropertiesData,
  IMaybeIType,
  IMaybe,
  IMaybeNull,
  IOptionalIType,
  OptionalDefaultValueOrFunction,
  ValidOptionalValue,
  ValidOptionalValues,
  getMembers,
  getPropertyMembers,
  TypeOfValue,
  cast,
  castToSnapshot,
  castToReferenceSnapshot,
  isArrayType,
  isFrozenType,
  isIdentifierType,
  isLateType,
  isLiteralType,
  isMapType,
  isModelType,
  isOptionalType,
  isPrimitiveType,
  isReferenceType,
  isRefinementType,
  isUnionType,
  tryReference,
  isValidReference,
  OnReferenceInvalidated,
  OnReferenceInvalidatedEvent,
  ReferenceOptions,
  ReferenceOptionsGetSet,
  ReferenceOptionsOnInvalidated,
  ReferenceIdentifier,
  ISnapshotProcessor,
  ISnapshotProcessors,
  getNodeId,
  IActionContext,
  getRunningActionContext,
  isActionContextChildOf,
  isActionContextThisOrChildOf,
  types,
  toGeneratorFunction,
  toGenerator,
} from './internal';
